name: Publish nightly build
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  build:
    name: Publish nightly build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - uses: actions/setup-dotnet@v2
      with:
        dotnet-version: "6.0.x"
    - name: Prepare single file executable
      run: dotnet publish GnucashPlDataImportGeneratorApp/GnucashPlDataImportGeneratorApp.csproj --configuration Release --output "./PublishResult/"
    - uses: actions/upload-artifact@v3
      with:
        name: AppExecutable
        path: PublishResult/GnucashPlDataImportGeneratorApp.exe